export const data = {
  username: "username",
  password: "password",
  invalidUsername: "user",
  invalidPassword: "word",
  emptyString: " ",
  inputBorder: "1px solid rgb(236, 151, 45)",
  fontFamily: "Arial, Helvetica, sans-serif",
  backgroundcolor: "rgb(202 129 37)",
};

export const RegisterData = {
  Username: "sdsdgsxs",
  Password: "RazMark25540197",
  Confirm: "RazMark25540197",
  inputBorder: "1px solid rgb(236, 151, 45)",
  fontFamily: "Arial, Helvetica, sans-serif",
  backgroundcolor: "rgb(202 129 37)",
  color: "rgb(57, 121, 170)",
  FirstName: "Razmik",
  LastName: "Markosyan",
  Address: "Dro 26",
  City: "Yararat",
  State: "Yarat",
  ZipCode: "06049814",
  Phone: "0983646566811",
  SSN: "281197476214",
};
 
export const homeAttributes = {
  ATMservices: "ATM Services",
  withdrawFunds: "Withdraw Funds",
  transferFunds: "Transfer Funds",
  checkBalances: "Check Balances",
  makeDeposits: "Make Deposits",
  onlineServices: "Online Services",
  billPay: "Bill Pay",
  accountHistory: "Account History",
  transferFunds1: "Transfer Funds",
  day: "04/15/2023",
  paraBankIsNowRe_Opened: "ParaBank Is Now Re-Opened",
  newOnlineBillPay: "New! Online Bill Pay",
  newOnlineAccountTransfers: "New! Online Account Transfers",
  parabankindex: "/parabank/index.htm",
  verifyaboutUs: 'ParaSoft Demo Website',
  successAboutUs: '/parabank/register.htm',
  servicesU: '/parabank/services.htm'
};
 export const autoExerciseData = {
  Day: '18',
  Month: 'November',
  Year: '1997',
  State: 'New York',
  City: 'New York',
  Password: 'RMaa181197',
  ExpiryMonth:"11",
  ExpiryYear: "2025",
  CVC: "695",
  CardName:"Historical",
  CardNumber:"4502555121455278",
  FirstText: "Added!",
  SecondText:"Your product has been added to cart.",
  CheckoutFirstText:"Checkout",
  CheckoutSecondText:"Register / Login account to proceed on checkout.",
  EmailAddress:"testbjKQA@gmail.com",
  Comment:"Thank you very much",
  DataTestCaseBtn:"Test Cases",
  DataApisBtn:"APIs list for practice",
  CaruselsThirdText:"All QA engineers can use this website for automation practice and API testing either they are at beginner or advance level. This is for everybody to help them brush up their automation skills",
  CaruselsSecondText:"Full-Fledged practice website for Automation Engineers",
  CaruselsFirstText:"Automation"
 }